from __future__ import annotations

# Canonical curated universe for the current production system.
# This is still a fixed universe, but it is no longer limited to 9 instruments.
# It now spans 100 liquid and widely followed ETFs/stocks across:
# - US broad equity
# - global / developed / emerging equity
# - sector and factor sleeves
# - rates / credit / inflation / muni fixed income
# - commodities / real assets
# - large-cap single-name equities

ASSET_REGISTRY = {
    "SPY": {"asset_class": "stocks", "sector": "broad_equity", "country": "us", "style": "core_growth"},
    "IVV": {"asset_class": "stocks", "sector": "broad_equity", "country": "us", "style": "core_growth"},
    "VOO": {"asset_class": "stocks", "sector": "broad_equity", "country": "us", "style": "core_growth"},
    "VTI": {"asset_class": "stocks", "sector": "broad_equity", "country": "us", "style": "core_growth"},
    "QQQ": {"asset_class": "stocks", "sector": "technology", "country": "us", "style": "growth"},
    "DIA": {"asset_class": "stocks", "sector": "industrials", "country": "us", "style": "core_growth"},
    "IWM": {"asset_class": "stocks", "sector": "small_cap", "country": "us", "style": "core_growth"},
    "RSP": {"asset_class": "stocks", "sector": "broad_equity", "country": "us", "style": "core_growth"},
    "VT": {"asset_class": "stocks", "sector": "global_equity", "country": "global", "style": "core_growth"},
    "ACWI": {"asset_class": "stocks", "sector": "global_equity", "country": "global", "style": "core_growth"},
    "EFA": {"asset_class": "stocks", "sector": "developed_equity", "country": "developed_ex_us", "style": "core_growth"},
    "IEFA": {"asset_class": "stocks", "sector": "developed_equity", "country": "developed_ex_us", "style": "core_growth"},
    "EEM": {"asset_class": "stocks", "sector": "emerging_markets", "country": "emerging_markets", "style": "growth"},
    "VEA": {"asset_class": "stocks", "sector": "developed_equity", "country": "developed_ex_us", "style": "core_growth"},
    "VWO": {"asset_class": "stocks", "sector": "emerging_markets", "country": "emerging_markets", "style": "growth"},
    "VGK": {"asset_class": "stocks", "sector": "europe", "country": "europe", "style": "core_growth"},
    "EWJ": {"asset_class": "stocks", "sector": "japan", "country": "japan", "style": "core_growth"},
    "FXI": {"asset_class": "stocks", "sector": "china", "country": "china", "style": "growth"},
    "INDA": {"asset_class": "stocks", "sector": "india", "country": "india", "style": "growth"},
    "EWC": {"asset_class": "stocks", "sector": "canada", "country": "canada", "style": "core_growth"},
    "XLK": {"asset_class": "stocks", "sector": "technology", "country": "us", "style": "growth"},
    "XLF": {"asset_class": "stocks", "sector": "financials", "country": "us", "style": "cyclical_income"},
    "XLV": {"asset_class": "stocks", "sector": "healthcare", "country": "us", "style": "income_defensive"},
    "XLE": {"asset_class": "stocks", "sector": "energy", "country": "us", "style": "cyclical_income"},
    "XLI": {"asset_class": "stocks", "sector": "industrials", "country": "us", "style": "core_growth"},
    "XLP": {"asset_class": "stocks", "sector": "consumer_staples", "country": "us", "style": "income_defensive"},
    "XLY": {"asset_class": "stocks", "sector": "consumer_discretionary", "country": "us", "style": "growth"},
    "XLU": {"asset_class": "stocks", "sector": "utilities", "country": "us", "style": "income_defensive"},
    "XLB": {"asset_class": "stocks", "sector": "materials", "country": "us", "style": "cyclical_income"},
    "XLRE": {"asset_class": "stocks", "sector": "real_estate", "country": "us", "style": "income_defensive"},
    "SMH": {"asset_class": "stocks", "sector": "semiconductors", "country": "us", "style": "growth"},
    "SOXX": {"asset_class": "stocks", "sector": "semiconductors", "country": "us", "style": "growth"},
    "XBI": {"asset_class": "stocks", "sector": "biotech", "country": "us", "style": "growth"},
    "VNQ": {"asset_class": "stocks", "sector": "real_estate", "country": "us", "style": "income_defensive"},
    "IYR": {"asset_class": "stocks", "sector": "real_estate", "country": "us", "style": "income_defensive"},
    "TLT": {"asset_class": "bonds", "sector": "fixed_income", "country": "us", "style": "income_defensive"},
    "IEF": {"asset_class": "bonds", "sector": "fixed_income", "country": "us", "style": "income_defensive"},
    "SHY": {"asset_class": "bonds", "sector": "fixed_income", "country": "us", "style": "income_defensive"},
    "TIP": {"asset_class": "bonds", "sector": "inflation_linked", "country": "us", "style": "income_defensive"},
    "LQD": {"asset_class": "bonds", "sector": "credit", "country": "us", "style": "income_defensive"},
    "HYG": {"asset_class": "bonds", "sector": "high_yield", "country": "us", "style": "cyclical_income"},
    "BND": {"asset_class": "bonds", "sector": "fixed_income", "country": "us", "style": "income_defensive"},
    "AGG": {"asset_class": "bonds", "sector": "fixed_income", "country": "us", "style": "income_defensive"},
    "EMB": {"asset_class": "bonds", "sector": "emerging_debt", "country": "emerging_markets", "style": "income_defensive"},
    "MUB": {"asset_class": "bonds", "sector": "municipal_bonds", "country": "us", "style": "income_defensive"},
    "GLD": {"asset_class": "commodities", "sector": "commodities", "country": "global", "style": "defensive_hedge"},
    "SLV": {"asset_class": "commodities", "sector": "commodities", "country": "global", "style": "defensive_hedge"},
    "USO": {"asset_class": "commodities", "sector": "energy_commodities", "country": "global", "style": "cyclical_income"},
    "UNG": {"asset_class": "commodities", "sector": "energy_commodities", "country": "global", "style": "cyclical_income"},
    "DBA": {"asset_class": "commodities", "sector": "agriculture", "country": "global", "style": "defensive_hedge"},
    "AAPL": {"asset_class": "stocks", "sector": "technology", "country": "us", "style": "growth"},
    "MSFT": {"asset_class": "stocks", "sector": "technology", "country": "us", "style": "growth"},
    "NVDA": {"asset_class": "stocks", "sector": "semiconductors", "country": "us", "style": "growth"},
    "AMZN": {"asset_class": "stocks", "sector": "consumer_discretionary", "country": "us", "style": "growth"},
    "GOOGL": {"asset_class": "stocks", "sector": "communication_services", "country": "us", "style": "growth"},
    "META": {"asset_class": "stocks", "sector": "communication_services", "country": "us", "style": "growth"},
    "TSLA": {"asset_class": "stocks", "sector": "consumer_discretionary", "country": "us", "style": "growth"},
    "JPM": {"asset_class": "stocks", "sector": "financials", "country": "us", "style": "cyclical_income"},
    "BAC": {"asset_class": "stocks", "sector": "financials", "country": "us", "style": "cyclical_income"},
    "GS": {"asset_class": "stocks", "sector": "financials", "country": "us", "style": "cyclical_income"},
    "MS": {"asset_class": "stocks", "sector": "financials", "country": "us", "style": "cyclical_income"},
    "JNJ": {"asset_class": "stocks", "sector": "healthcare", "country": "us", "style": "income_defensive"},
    "UNH": {"asset_class": "stocks", "sector": "healthcare", "country": "us", "style": "income_defensive"},
    "ABBV": {"asset_class": "stocks", "sector": "healthcare", "country": "us", "style": "income_defensive"},
    "MRK": {"asset_class": "stocks", "sector": "healthcare", "country": "us", "style": "income_defensive"},
    "XOM": {"asset_class": "stocks", "sector": "energy", "country": "us", "style": "cyclical_income"},
    "CVX": {"asset_class": "stocks", "sector": "energy", "country": "us", "style": "cyclical_income"},
    "PG": {"asset_class": "stocks", "sector": "consumer_staples", "country": "us", "style": "income_defensive"},
    "KO": {"asset_class": "stocks", "sector": "consumer_staples", "country": "us", "style": "income_defensive"},
    "PEP": {"asset_class": "stocks", "sector": "consumer_staples", "country": "us", "style": "income_defensive"},
    "WMT": {"asset_class": "stocks", "sector": "consumer_staples", "country": "us", "style": "income_defensive"},
    "COST": {"asset_class": "stocks", "sector": "consumer_staples", "country": "us", "style": "core_growth"},
    "HD": {"asset_class": "stocks", "sector": "consumer_discretionary", "country": "us", "style": "core_growth"},
    "MCD": {"asset_class": "stocks", "sector": "consumer_discretionary", "country": "us", "style": "income_defensive"},
    "NKE": {"asset_class": "stocks", "sector": "consumer_discretionary", "country": "us", "style": "growth"},
    "CAT": {"asset_class": "stocks", "sector": "industrials", "country": "us", "style": "cyclical_income"},
    "GE": {"asset_class": "stocks", "sector": "industrials", "country": "us", "style": "core_growth"},
    "RTX": {"asset_class": "stocks", "sector": "industrials", "country": "us", "style": "income_defensive"},
    "LIN": {"asset_class": "stocks", "sector": "materials", "country": "us", "style": "core_growth"},
    "PLD": {"asset_class": "stocks", "sector": "real_estate", "country": "us", "style": "income_defensive"},
    "ORCL": {"asset_class": "stocks", "sector": "technology", "country": "us", "style": "core_growth"},
    "CRM": {"asset_class": "stocks", "sector": "technology", "country": "us", "style": "growth"},
    "ADBE": {"asset_class": "stocks", "sector": "technology", "country": "us", "style": "growth"},
    "CSCO": {"asset_class": "stocks", "sector": "technology", "country": "us", "style": "income_defensive"},
    "QCOM": {"asset_class": "stocks", "sector": "semiconductors", "country": "us", "style": "growth"},
    "AMD": {"asset_class": "stocks", "sector": "semiconductors", "country": "us", "style": "growth"},
    "AVGO": {"asset_class": "stocks", "sector": "semiconductors", "country": "us", "style": "growth"},
    "AMAT": {"asset_class": "stocks", "sector": "semiconductors", "country": "us", "style": "growth"},
    "NFLX": {"asset_class": "stocks", "sector": "communication_services", "country": "us", "style": "growth"},
    "DIS": {"asset_class": "stocks", "sector": "communication_services", "country": "us", "style": "core_growth"},
    "V": {"asset_class": "stocks", "sector": "financials", "country": "us", "style": "core_growth"},
    "MA": {"asset_class": "stocks", "sector": "financials", "country": "us", "style": "core_growth"},
    "TMUS": {"asset_class": "stocks", "sector": "communication_services", "country": "us", "style": "growth"},
    "TMO": {"asset_class": "stocks", "sector": "healthcare", "country": "us", "style": "core_growth"},
    "ACN": {"asset_class": "stocks", "sector": "technology", "country": "us", "style": "core_growth"},
    "INTU": {"asset_class": "stocks", "sector": "technology", "country": "us", "style": "growth"},
    "IBM": {"asset_class": "stocks", "sector": "technology", "country": "us", "style": "income_defensive"},
    "BKNG": {"asset_class": "stocks", "sector": "consumer_discretionary", "country": "us", "style": "growth"},
    "BRK-B": {"asset_class": "stocks", "sector": "financials", "country": "us", "style": "core_growth"},
    "HON": {"asset_class": "stocks", "sector": "industrials", "country": "us", "style": "core_growth"},
}


STANDARD_UNIVERSE = list(ASSET_REGISTRY.keys())

ASSET_CLASS_MAP = {ticker: metadata["asset_class"] for ticker, metadata in ASSET_REGISTRY.items()}
ASSET_SECTOR_MAP = {ticker: metadata["sector"] for ticker, metadata in ASSET_REGISTRY.items()}
ASSET_COUNTRY_MAP = {ticker: metadata["country"] for ticker, metadata in ASSET_REGISTRY.items()}
ASSET_STYLE_MAP = {ticker: metadata["style"] for ticker, metadata in ASSET_REGISTRY.items()}
